// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/dynamodb/dynamodb.go

// Package dynamodb is a generated GoMock package.
package dynamodb

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DeleteItem mocks base method.
func (m *MockService) DeleteItem(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockServiceMockRecorder) DeleteItem(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockService)(nil).DeleteItem), key)
}

// GetItem mocks base method.
func (m *MockService) GetItem(key string) (*Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", key)
	ret0, _ := ret[0].(*Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockServiceMockRecorder) GetItem(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockService)(nil).GetItem), key)
}

// PutItem mocks base method.
func (m *MockService) PutItem(key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutItem", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutItem indicates an expected call of PutItem.
func (mr *MockServiceMockRecorder) PutItem(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutItem", reflect.TypeOf((*MockService)(nil).PutItem), key, value)
}
